version: '3.1'

services:
    db:
        image: postgres
        ports:
            - "5431:5432"
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres_jpa
            POSTGRES_DB: postgres_jpa